name: code-quality-check
on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  code-quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Run Unit Tests with Coverage
        run: |
          go test -coverprofile=coverage.out ./...

      - name: Check Coverage Threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Coverage is below threshold: $COVERAGE%"
            exit 1
          else
            echo "Coverage meets threshold: $COVERAGE%"
          fi

      - name: Execute vet
        run: go vet ./...
